### ISSUE TITLE
draw circos for mitogenome how to plot additional features besides CDS, rRNA, tRNA

### ISSUE THREAD

**Issue by HowieJM** [comery/Data-Visulization#1]
Hi Comery, 

I have a more detailed version of this question over on the MitoZ issue page, but I thought I’d try here too.

Do you have a simple way I could edit the draw_circos_for_mitogenome_auto_depth.pl script and the config file such that when I run the script I can plot CDS, rRNA, tRNA [like at present], but can also plot locations of other features in the GenBank file in different colours but on the same circos plot. The example would be that I have a D-loop control region feature, it would be nice to plot it in blue. At present, I can edit the .gbf to make it a gene feature, then it will be plotted, but the colour will be locked to be that of the CDS, rRNA or tRNA.

Any help much appreciated :)

Also, very nice bits of code and super helpful scripts, so thanks that you wrote them!

Cheers,
James

**Comment by comery** [comment]
Hi James,

It's interesting that you can find my repository here! 

I replied to your question in [issue#123](https://github.com/linzhi2013/MitoZ/issues/123) of MitoZ. I have updated the draw_circos_for_mitogenome_auto_depth.pl script. It can accept the D-loop feature and make a plot.
